#!/usr/bin/env python3
# Author: Kurt Irvin Rojas
# https://github.com/kimrojas/smith_utils
"""
SMITH CONNECT
    A "smart" connection login utility for smith. 
    This will automatically decide if you will connect 
    using a local or global ssh protocol with local as priority.
    No more manual ssh typing.
"""
import sys, os, subprocess
sys.dont_write_bytecode = True
from smith_user_parse import user
import smith_check
from smith_output import blue, green, warning, fail, bold, underline


print(green(f"CONNECTING TO SMITH SERVER ({user['smith_username']})"))
print(green(f"{'-'*53}"))

method = smith_check.check()

if method == 'UseLocal': bashCommand = f"ssh -Y {user['smith_username']}@{user['smith_ip']}"
if method == 'UseGlobal': bashCommand = f"ssh -Y {user['smith_username']}@localhost -p {user['smith_univ_port']}"

output = subprocess.run(bashCommand, shell=True)

if output.returncode != 0:
    print(fail(f"{'-'*53}"))
    print(green("CONNECTION FAILURE"))
    sys.exit()

print(green(f"{'-'*53}"))
print(green("CONNECTION TERMINATED"))
